has_layout:
  true

layout:
  default

#layouts
default:
  title: >
    common use title - blahblahblahblah

  metas:
    https:
      content-type: 'text/html; charset=utf-8'
      content-language: 'en-US'

    name:
      keywords: > blah, more blah, something about blah
      description: description about site blah
      robots: > index, follow

  css:
    site:
      - common/reset
      - common/util
      - common/header
      - common/main

  js:
    cdn:
      - https://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min    